name: flutter_app_template
description: A new Flutter project.
publish_to: none
version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8

  # Logger
  simple_logger:

  # LocalDatabase
  shared_preferences: ^2.5.2

  # Riverpod
  hooks_riverpod:
  riverpod_annotation: ^2.6.1

  # Hooks
  flutter_hooks:

  # Entity
  freezed_annotation: ^3.0.0
  json_annotation: ^4.9.0
  equatable:

  # Dialog
  adaptive_dialog:

  # Access local storage
  path_provider:

  # Date
  intl:

  # Reactive
  rxdart:

  # Data share
  share_plus:

  # WebView
  flutter_inappwebview: ^6.1.5

  # Launcher
  url_launcher:
  map_launcher:

  # Transition
  page_transition:

  # Image
  image_picker:
  image_gallery_saver_plus: ^4.0.1
  image_cropper:
  flutter_image_compress:
  extended_image:
  flutter_svg:

  # Picker
  numberpicker:

  # PullToRefresh
  pull_to_refresh_flutter3:

  # Permission
  permission_handler:

  # Firebase
  firebase_core: ^3.12.1
  firebase_analytics: ^11.4.4
  cloud_firestore: ^5.6.5
  firebase_auth: ^5.5.1
  firebase_storage: ^12.4.4
  cloud_functions: ^5.3.4
  firebase_messaging: ^15.2.4
  firebase_crashlytics: ^4.3.4
  firebase_remote_config: ^5.4.2

  # LocalNotification
  flutter_local_notifications:
  flutter_timezone:
  timezone:

  # Api
  retrofit:
  dio:

  # Navigation
  go_router:

  # Info
  package_info_plus:
  device_info_plus:

  # Text
  flutter_linkify:

  # Widget
  flutter_slidable:
  dismissible_page:

  # Other
  uuid:
  synchronized:
  hashids2:
  collection:
  quiver:

dev_dependencies:
  # Test
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter
  mockito: ^5.4.5

  # Static analysis
  pedantic_mono: ^1.30.3
  custom_lint: ^0.7.5
  riverpod_lint: ^2.6.5

  # Serializer
  json_serializable: ^6.9.4

  # Code generator
  build_runner: ^2.4.15
  freezed: ^3.0.3
  flutter_gen_runner: ^5.10.0
  retrofit_generator: ^9.1.9
  riverpod_generator: ^2.6.5

  # Other
  flutter_launcher_icons:

flutter_gen:
  output: lib/core/res/gen/
  colors:
    inputs:
      - assets/color/colors.xml

flutter:
  uses-material-design: true
  assets:
    - assets/images/

  # カスタムフォントを利用する場合はここを設定する
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
# flutter_launcher_iconsを利用してアイコンのリサイズする場合はここを設定する
#flutter_icons:
#  android: true
#  ios: true
#  image_path_android: "assets/icon/icon_android.png"
#  image_path_ios: "assets/icon/icon_ios.png"
#  adaptive_icon_foreground: "assets/icon/adaptive_icon_foreground.png"
#  adaptive_icon_background: "#F4A281"

