name: flutter_app_template
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8

  # LocalDatabase
  shared_preferences:

  # Riverpod
  hooks_riverpod:
  riverpod_annotation: ^2.6.1

  # Hooks
  flutter_hooks:

  # PullToRefresh
  pull_to_refresh_flutter3:

  # Api
  retrofit:
  dio:

  # Entity
  freezed_annotation: ^3.0.0

  # Launcher
  url_launcher:

  # Image
  extended_image:

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Testing
  mockito: ^5.4.5

  # Static analysis
  pedantic_mono: ^1.30.3
  custom_lint: ^0.7.5
  riverpod_lint: ^2.6.5

  # Serializer
  json_serializable: ^6.9.4

  # Code generator
  build_runner: ^2.4.15
  freezed: ^3.0.3
  riverpod_generator: ^2.6.5
  retrofit_generator: ^9.1.9

flutter:
  uses-material-design: true
